### ISSUE TITLE
Strange behaviour when running from within zsh

### ISSUE THREAD

**Issue by hannorein** [carlislewishard/swiftest#14]
When running one of the examples (who_gr_test) the simulation seems to initialize correctly, but then then stops at t=0. I get back to my shell but I don't see any output from any commands anymore. Strangely, when I type exit, I get back to the simulation?! The simulation then runs as expected. I have no clue what is happening!

I use zsh as my default shell. 

https://github.com/openjournals/joss-reviews/issues/5409

**Comment by profminton** [comment]
I also use zsh and have not encountered this, though I will say that some of the handling of shell stuff is a bit wonkier than I'd like.  I pass the login shell option `-l` so that it sets environment variables correctly (for shared libraries, etc), but I've always suspected that it is not robust. I will investigate this some more and see if I can come up with a more robust method of executing the driver from within the Python scripts

**Comment by hannorein** [comment]
I see. I'm not sure if this is the right way of doing it. FWIW, I think ideally you don't want to call a bash script with subprocess.open, but the executable directly.
