### ISSUE TITLE
examples/Chambers2013 errors

### ISSUE THREAD

**Issue by aatrani** [carlislewishard/swiftest#19]
I successfully ran the swiftest_driver executable in examples/Chambers2013. 

First, note that if you run `swiftest_driver` from another folder than `simdata`, Swiftest terminates in error:
```
Terminating Swiftest (version 1.0) due to error!!
------------------------------------------------
ERROR STOP 

Error termination. Backtrace:
#0  0x7f583e2238b2 in ???
#1  0x7f583e2243b9 in ???
#2  0x7f583e225727 in ???
#3  0x40f5b5 in ???
#4  0x4de92b in ???
#5  0x4d81b4 in ???
#6  0x4cac7d in ???
#7  0x464196 in ???
#8  0x45427e in ???
#9  0x486cdd in ???
#10  0x48b813 in ???
#11  0x40381c in ???
#12  0x7f583e049b49 in ???
#13  0x7f583e049c0a in ???
#14  0x403854 in ???
#15  0xffffffffffffffff in ???

```
The error is confusing and would be better to explicitly say that the working directory needs to be the same as where param.in exists.

I tried to run `scattermovie.py`, but I got the following error:
```
py scattermovie.py 
Reading Swiftest file /home/lex/Work/codes/swiftest/examples/Chambers2013/simdata/param.in

Creating Dataset from NetCDF file
Traceback (most recent call last):
  File "swiftest/examples/Chambers2013/scattermovie.py", line 155, in <module>
    sim = swiftest.Simulation(read_data=True, read_collisions=False, dask=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "swiftest/python/swiftest/swiftest/simulation_class.py", line 373, in __init__
    if self.read_param(read_init_cond = True, dask=dask, **kwargs):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "swiftest/python/swiftest/swiftest/simulation_class.py", line 2679, in read_param
    self.data = io.swiftest2xr(param_tmp, verbose=self.verbose, dask=dask)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "swiftest/python/swiftest/swiftest/io.py", line 643, in swiftest2xr
    ds = xr.open_mfdataset(param['BIN_OUT'], engine='h5netcdf', mask_and_scale=False)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xarray/backends/api.py", line 982, in open_mfdataset
    datasets = [open_(p, **open_kwargs) for p in paths]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xarray/backends/api.py", line 982, in <listcomp>
    datasets = [open_(p, **open_kwargs) for p in paths]
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xarray/backends/api.py", line 511, in open_dataset
    backend = plugins.get_backend(engine)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xarray/backends/plugins.py", line 205, in get_backend
    raise ValueError(
ValueError: unrecognized engine h5netcdf must be one of: ['netcdf4', 'scipy', 'store']
```
I have xarray version 2023.4.2

Changing `h5netcdf` to `netcdf4` in swiftest/io.py fixed the error, but the script took more than 20 minutes to produce the first video (aescatter) and a 30% of the second video (aiscatter). Is that normal?

**Comment by profminton** [comment]
A lot has changed since this issue was opened, but I finally got around to addressing it directly. In the latest release (v2023.10.1) I modified the Chambers 2013 example to include a script that will run a very short test case so that one can troubleshoot the movie scripts. Unfortunately the movie scripts make use of ffmpeg, and there's no good way to include that in a Python package dependency list, as it has to be installed natively (via Homebrew, apt, yum, etc) or in conda. So I added some text to the script docstrings to warn that the scripts need that installed first. 

The short test simulations run quickly and are processed quickly. For very long simulations, post-processing time will increase. Because we use Dask for post-processing, it will benefit from being run in parallel. To improve things further, the movie scripts could be rewritten so that the simulation and movie frame processing happen concurrently.
