### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by hannorein** [carlislewishard/swiftest#5]
As #mikegrudic has pointed out, I also can't find any automated tests. Do you plan to add them?

#openjournals/joss-reviews/issues/5409

**Comment by carlislewishard** [comment]
Hanno, 

Yes, I plan to add one. I hope to get to it this afternoon so be on the lookout for that. Have you been able to get things compiled and running on your end?

Carlisle

**Comment by hannorein** [comment]
In a container, yes.

**Comment by carlislewishard** [comment]
It turns out that creating automatic tests in CMAKE was more straightforward than I thought and I was able to get to it this afternoon. Now, when you type 'make', three python scripts located in the examples/Basic_Simulation directory should run in sequence. The first script (initial_conditions.py) should generate some initial conditions, run a short program (< 10 sec), and save the output. The second script (output_reader.py) should read in the output from the first program and create a plot. The third script (errors.py) should also read in the output from the first program and check that the angular momentum, energy, and mass errors are reasonable and then report those errors to the terminal. Give this a try when you get the chance and I look forward to your feedback.

**Comment by hannorein** [comment]
Great! Three quick queries...

1) Do I read it correctly that your tests depend on a random number generator? If so it might make sense to either just fix the numbers, or use a fixed seed so that the tests are the same every time. Otherwise, you might get unlucky at some point with the unit tests failing/passing for no obvious reason. 
2) Why is the relative energy error threshold 1e-4 in your test? Seems a little high? Maybe a less violent system works better as a test?
3) How do you test the accuracy for test particles?

**Comment by carlislewishard** [comment]
@hannorein Great points. 

1. I set a seed in the initial_conditions.py script so that the random number generator creates the same system every time you run the script. 

2. I decreased the energy of the system slightly so the energy error is a bit lower (-7.18e-6 for the Basic_Simulation example). The energy errors in Swiftest are characteristically a bit higher than the angular momentum errors (1.09e-11 for the Basic_Simulation example) and mass errors (0.0 for the Basic_Simulation example). Much of our early development was aimed at beating down angular momentum and mass errors as those are physically more meaningful. The energy error is well bounded, even in longer runs, so we have not focused too much of rooting out minor bugs that could be affecting the energy error. This is definitely something we should add to our to do list, but for now it doesn't seem to be affecting the performance of the code or the results of the runs.

3. In errors.py, we use the entire angular momentum, mass, and energy of the system to calculate the errors. So test particles are included in that calculation.

**Comment by hannorein** [comment]
Thanks. But regarding 3: test particles don't have angular momentum, mass or energy? E= 1/2*m*v^2 is 0 if m=0.

**Comment by carlislewishard** [comment]
Ahh, yes. I suppose our current tests just check to make sure that test particles _aren't_ affecting the errors in any unpredictable ways. Let me think about the best way to go about verifying that test particles are behaving as they should and get back to you.

**Comment by profminton** [comment]
Automated tests are now incorporated in the build process via `cibuildwheel`. It is a very minimal set of tests at the moment. It is just checking that it can generate valid NetCDF initial conditions files, and run a basic simulation using all of the integrators. More tests are possible and planned, but this basic functionality is good for ensuring that the code at least runs on whatever system it is being built for.
