### ISSUE TITLE
Python requirements contains local files and probably unnecessary modules

### ISSUE THREAD

**Issue by warrickball** [carlislewishard/swiftest#9]
Hi,

The [requirements file in the Python module](https://github.com/carlislewishard/swiftest/blob/master/python/swiftest/requirements.txt) contains lots of lines like
```
attrs @ file:///tmp/build/80754af9/attrs_1620827162558/work
backcall @ file:///home/ktietz/src/ci/backcall_1611930011877/work
```
as well as lots of fixed versions, including of things that I doubt are requirements, e.g.
```
jupyter==1.0.0
```
I presume the Swiftest Python module doesn't actually depend on Jupyter...

I suspect that this is just a dump/freeze of everything someone had installed, possibly in a Conda environment, but it might stump anyone who tries
```
$ python3 -m pip install -r requirements.txt
```
The [top-level list of requirements](https://github.com/carlislewishard/swiftest/blob/master/environment.yml) looks actively curated, so you might want to draw on that to get a list of Python module requirements that work.

Like automated tests (#5), building the Python module in a fresh environment is something that can be done with continuous integration.

**Comment by profminton** [comment]
I carefully went through the package list and tried to set minimum versions of independently-required packages that will work with all of our machines and shouldn't break anything. I'm looking into CI and also packing pre-compiled binaries into a wheel so that we can simply install the package in one pip command, but I'm still educating myself on how to do that.
